export const categories = [
  { label: "technology", value: "Technology" },
  { label: "science", value: "Science" },
  { label: "health", value: "Health and Wellness" },
  { label: "lifestyle", value: "Lifestyle" },
  { label: "travel", value: "Travel" },
  { label: "food", value: "Food and Cooking" },
  { label: "fashion", value: "Fashion and Beauty" },
  { label: "development", value: "Personal Development" },
  { label: "finance", value: "Finance and Investing" },
  { label: "business", value: "Business and Entrepreneurship" },
  { label: "parenting", value: "Parenting" },
  { label: "education", value: "Education" },
  { label: "art", value: "Art and Culture" },
  { label: "sports", value: "Sports and Fitness" },
  { label: "home", value: "Home and Decor" },
  { label: "gaming", value: "Gaming" },
  { label: "entertainment", value: "Entertainment and Pop Culture" },
  { label: "news", value: "News and Current Events" },
  { label: "sustainability", value: "Sustainability and Environment" },
  { label: "selfcare", value: "Self-Care and Mental Health" },
  { label: "howto", value: "How-to Guides and Tutorials" },
  { label: "career", value: "Career Advice" },
  { label: "music", value: "Music" },
  { label: "inspiration", value: "Inspirational Stories" },
  { label: "socialmedia", value: "Social Media and Marketing" },
  { label: "photography", value: "Photography" },
  { label: "gardening", value: "Gardening" },
  { label: "pets", value: "Pet Care" },
  { label: "diy", value: "DIY and Crafts" },
  { label: "relationship", value: "Relationship and Dating" },
  { label: "history", value: "History and Archaeology" },
  { label: "outdoor", value: "Outdoor Adventures" },
  { label: "scifi", value: "Science Fiction and Fantasy" },
  { label: "cars", value: "Cars and Automobiles" },
  { label: "fitness", value: "Fitness and Exercise" },
  { label: "meditation", value: "Meditation and Mindfulness" },
  { label: "parentingtips", value: "Parenting Tips and Advice" },
  { label: "organization", value: "Home Organization and Decluttering" },
  { label: "language", value: "Language Learning and Linguistics" },
  { label: "beauty", value: "Beauty and Skincare" },
  { label: "financez", value: "Personal Finance and Budgeting" },
  { label: "wedding", value: "Wedding Planning and Inspiration" },
  { label: "writing", value: "Writing and Publishing" },
  { label: "socialissues", value: "Social Issues and Activism" },
  { label: "productivity", value: "Productivity and Time Management" },
  { label: "homeremedies", value: "Home Remedies and Natural Health" },
  { label: "comedy", value: "Comedy and Humor" },
  { label: "fashionstyle", value: "Fashion and Style" },
  { label: "techtrends", value: "Technology Trends" },
  { label: "traveltips", value: "Travel Tips and Guides" },
];

export const languages = [
  { label: "Afrikaans", value: "Afrikaans" },
  { label: "Albanian", value: "Albanian" },
  { label: "Amharic", value: "Amharic" },
  { label: "Arabic", value: "Arabic" },
  { label: "Armenian", value: "Armenian" },
  { label: "Azerbaijani", value: "Azerbaijani" },
  { label: "Basque", value: "Basque" },
  { label: "Belarusian", value: "Belarusian" },
  { label: "Bengali", value: "Bengali" },
  { label: "Bosnian", value: "Bosnian" },
  { label: "Bulgarian", value: "Bulgarian" },
  { label: "Catalan", value: "Catalan" },
  { label: "Cebuano", value: "Cebuano" },
  { label: "Chichewa", value: "Chichewa" },
  { label: "Chinese (Simplified)", value: "Chinese (Simplified)" },
  { label: "Chinese (Traditional)", value: "Chinese (Traditional)" },
  { label: "Corsican", value: "Corsican" },
  { label: "Croatian", value: "Croatian" },
  { label: "Czech", value: "Czech" },
  { label: "Danish", value: "Danish" },
  { label: "Dutch", value: "Dutch" },
  { label: "English", value: "English" },
  { label: "Esperanto", value: "Esperanto" },
  { label: "Estonian", value: "Estonian" },
  { label: "Filipino", value: "Filipino" },
  { label: "Finnish", value: "Finnish" },
  { label: "French", value: "French" },
  { label: "Frisian", value: "Frisian" },
  { label: "Galician", value: "Galician" },
  { label: "Georgian", value: "Georgian" },
  { label: "German", value: "German" },
  { label: "Greek", value: "Greek" },
  { label: "Gujarati", value: "Gujarati" },
  { label: "Haitian Creole", value: "Haitian Creole" },
  { label: "Hausa", value: "Hausa" },
  { label: "Hawaiian", value: "Hawaiian" },
  { label: "Hebrew", value: "Hebrew" },
  { label: "Hindi", value: "Hindi" },
  { label: "Hmong", value: "Hmong" },
  { label: "Hungarian", value: "Hungarian" },
  { label: "Icelandic", value: "Icelandic" },
  { label: "Igbo", value: "Igbo" },
  { label: "Indonesian", value: "Indonesian" },
  { label: "Irish", value: "Irish" },
  { label: "Italian", value: "Italian" },
  { label: "Japanese", value: "Japanese" },
  { label: "Javanese", value: "Javanese" },
  { label: "Kannada", value: "Kannada" },
  { label: "Kazakh", value: "Kazakh" },
  { label: "Khmer", value: "Khmer" },
  { label: "Korean", value: "Korean" },
  { label: "Kurdish (Kurmanji)", value: "Kurdish (Kurmanji)" },
  { label: "Kyrgyz", value: "Kyrgyz" },
  { label: "Lao", value: "Lao" },
  { label: "Latin", value: "Latin" },
  { label: "Latvian", value: "Latvian" },
  { label: "Lithuanian", value: "Lithuanian" },
  { label: "Luxembourgish", value: "Luxembourgish" },
  { label: "Macedonian", value: "Macedonian" },
  { label: "Malagasy", value: "Malagasy" },
  { label: "Malay", value: "Malay" },
  { label: "Malayalam", value: "Malayalam" },
  { label: "Maltese", value: "Maltese" },
  { label: "Maori", value: "Maori" },
  { label: "Marathi", value: "Marathi" },
  { label: "Mongolian", value: "Mongolian" },
  { label: "Myanmar (Burmese)", value: "Myanmar (Burmese)" },
  { label: "Nepali", value: "Nepali" },
  { label: "Norwegian", value: "Norwegian" },
  { label: "Odia", value: "Odia" },
  { label: "Pashto", value: "Pashto" },
  { label: "Persian", value: "Persian" },
  { label: "Polish", value: "Polish" },
  { label: "Portuguese", value: "Portuguese" },
  { label: "Punjabi", value: "Punjabi" },
  { label: "Romanian", value: "Romanian" },
  { label: "Russian", value: "Russian" },
  { label: "Samoan", value: "Samoan" },
  { label: "Scots Gaelic", value: "Scots Gaelic" },
  { label: "Serbian", value: "Serbian" },
  { label: "Sesotho", value: "Sesotho" },
  { label: "Shona", value: "Shona" },
  { label: "Sindhi", value: "Sindhi" },
  { label: "Sinhala", value: "Sinhala" },
  { label: "Slovak", value: "Slovak" },
  { label: "Slovenian", value: "Slovenian" },
  { label: "Somali", value: "Somali" },
  { label: "Spanish", value: "Spanish" },
  { label: "Sundanese", value: "Sundanese" },
  { label: "Swahili", value: "Swahili" },
  { label: "Swedish", value: "Swedish" },
  { label: "Tajik", value: "Tajik" },
  { label: "Tamil", value: "Tamil" },
  { label: "Tatar", value: "Tatar" },
  { label: "Telugu", value: "Telugu" },
  { label: "Thai", value: "Thai" },
  { label: "Turkish", value: "Turkish" },
  { label: "Turkmen", value: "Turkmen" },
  { label: "Ukrainian", value: "Ukrainian" },
  { label: "Urdu", value: "Urdu" },
  { label: "Uyghur", value: "Uyghur" },
  { label: "Uzbek", value: "Uzbek" },
  { label: "Vietnamese", value: "Vietnamese" },
  { label: "Welsh", value: "Welsh" },
  { label: "Xhosa", value: "Xhosa" },
  { label: "Yiddish", value: "Yiddish" },
  { label: "Yoruba", value: "Yoruba" },
  { label: "Zulu", value: "Zulu" },
];

export const tones = [
  { label: "Professional", value: "Professional" },
  { label: "Formal", value: "Formal" },
  { label: "Informative", value: "Informative" },
  { label: "Friendly", value: "Friendly" },
  { label: "Persuasive", value: "Persuasive" },
  { label: "Playful", value: "Playful" },
  { label: "Cautious", value: "Cautious" },
  { label: "Optimistic", value: "Optimistic" },
  { label: "Authoritative", value: "Authoritative" },
  { label: "Humorous", value: "Humorous" },
  { label: "Empathetic", value: "Empathetic" },
  { label: "Sarcastic", value: "Sarcastic" },
  { label: "Technical", value: "Technical" },
  { label: "Analytical", value: "Analytical" },
  { label: "Conversational", value: "Conversational" },
  { label: "Instructive", value: "Instructive" },
  { label: "Encouraging", value: "Encouraging" },
  { label: "Authoritative", value: "Authoritative" },
  { label: "Respectful", value: "Respectful" },
  { label: "Inspiring", value: "Inspiring" },
  { label: "Curious", value: "Curious" },
  { label: "Direct", value: "Direct" },
  { label: "Energetic", value: "Energetic" },
  { label: "Assertive", value: "Assertive" },
  { label: "Pragmatic", value: "Pragmatic" },
  { label: "Diplomatic", value: "Diplomatic" },
  { label: "Motivational", value: "Motivational" },
  { label: "Reflective", value: "Reflective" },
  { label: "Inspiring", value: "Inspiring" },
  { label: "Questioning", value: "Questioning" },
  { label: "Supportive", value: "Supportive" },
  { label: "Neutral", value: "Neutral" },
  { label: "Confident", value: "Confident" },
  { label: "Reassuring", value: "Reassuring" },
  { label: "Dramatic", value: "Dramatic" },
  { label: "Colloquial", value: "Colloquial" },
  { label: "Motivated", value: "Motivated" },
  { label: "Contemplative", value: "Contemplative" },
  { label: "Analytical", value: "Analytical" },
  { label: "Humble", value: "Humble" },
  { label: "Resolute", value: "Resolute" },
  { label: "Thoughtful", value: "Thoughtful" },
  { label: "Dynamic", value: "Dynamic" },
  { label: "Hopeful", value: "Hopeful" },
  { label: "Sincere", value: "Sincere" },
  { label: "Witty", value: "Witty" },
  { label: "Quizzical", value: "Quizzical" },
  { label: "Straightforward", value: "Straightforward" },
  { label: "Playful", value: "Playful" },
  { label: "Respectful", value: "Respectful" },
  { label: "Engaging", value: "Engaging" },
  { label: "Sarcastic", value: "Sarcastic" },
];

export const wrtingStyles = [
  { label: "Academic", value: "Academic" },
  { label: "Creative", value: "Creative" },
  { label: "Technical", value: "Technical" },
  { label: "Business", value: "Business" },
  { label: "Conversational", value: "Conversational" },
  { label: "Journalistic", value: "Journalistic" },
  { label: "Instructional", value: "Instructional" },
  { label: "Formal", value: "Formal" },
  { label: "Informative", value: "Informative" },
  { label: "Persuasive", value: "Persuasive" },
  { label: "Narrative", value: "Narrative" },
  { label: "Descriptive", value: "Descriptive" },
  { label: "Analytical", value: "Analytical" },
  { label: "Humorous", value: "Humorous" },
  { label: "Argumentative", value: "Argumentative" },
  { label: "Opinionated", value: "Opinionated" },
  { label: "Expository", value: "Expository" },
  { label: "Professional", value: "Professional" },
  { label: "Promotional", value: "Promotional" },
  { label: "Sarcastic", value: "Sarcastic" },
  { label: "Technical", value: "Technical" },
  { label: "Scholarly", value: "Scholarly" },
  { label: "Persuasive", value: "Persuasive" },
  { label: "Friendly", value: "Friendly" },
  { label: "Storytelling", value: "Storytelling" },
  { label: "Opinion Piece", value: "Opinion Piece" },
  { label: "Review", value: "Review" },
  { label: "Tutorial", value: "Tutorial" },
  { label: "Instructive", value: "Instructive" },
  { label: "Motivational", value: "Motivational" },
  { label: "Analytical", value: "Analytical" },
  { label: "Biographical", value: "Biographical" },
  { label: "Dramatic", value: "Dramatic" },
  { label: "Inspiring", value: "Inspiring" },
  { label: "Comparative", value: "Comparative" },
  { label: "Educational", value: "Educational" },
  { label: "Satirical", value: "Satirical" },
  { label: "Personal", value: "Personal" },
  { label: "Persuasive", value: "Persuasive" },
  { label: "Investigative", value: "Investigative" },
  { label: "Instructional", value: "Instructional" },
  { label: "Informal", value: "Informal" },
  { label: "Procedural", value: "Procedural" },
  { label: "Reflective", value: "Reflective" },
  { label: "Question and Answer", value: "Question and Answer" },
  { label: "Formal", value: "Formal" },
  { label: "Technical", value: "Technical" },
  { label: "Entertaining", value: "Entertaining" },
  { label: "Analytical", value: "Analytical" },
  { label: "Comedic", value: "Comedic" },
  { label: "Historical", value: "Historical" },
  { label: "Critical", value: "Critical" },
];


export const tools =[
  {
    id:0,
    title:"Article Generator",
    description:"Generate quality custom articles",
    icon:"enhance.png",
    categorie:"Article",
  },
  {
    id:1,
    title:"Article Enhancer",
    description:"Enhance an existing Text & get a rating",
    icon:"e.png",
    categorie:"Article",
  },
  {
    id:2,
    title:"Story",
    description:"Write a full story with little context",
    icon:".png",
    categorie:"long",
  },
  {
    id:3,
    title:"Script",
    description:"",
    icon:".png",
    categorie:"long",
  },{
    id:4,
    title:"Product list Workflow",
    description:"Workflow for mass production of product lists write a complete amazon product list in minutes",
    icon:".png",
    categorie:"Article",
  },{
    id:5,
    title:"FreeStyle",
    description:"a text editor and ai GO WILD !",
    icon:".png",
    categorie:"Article",
  },{
    id:6,
    title:"Prodcut review",
    description:"an in depth review of a single product , with pros and cons and a link to the product",
    icon:".png",
    categorie:"Article",
  },{
    id:7,
    title:"How to Guide",
    description:"",
    icon:".png",
    categorie:"Article",
  },
  {
    id:8,
    title:"documentation",
    description:"",
    icon:".png",
    categorie:"Article",
  }
]

/*
,{
    id:,
    title:"",
    description:"",
    icon:".png",
    categorie:"Article",
  },{
    id:,
    title:"",
    description:"",
    icon:".png",
    categorie:"Article",
  },{
    id:,
    title:"",
    description:"",
    icon:".png",
    categorie:"long",
  },
*/